### ISSUE TITLE
Uncaught TypeError: s.split is not a function

### ISSUE THREAD

**Issue by jamiewilson** [AddToCalendar/addtocalendar#4]
Not sure what happened as it was working fine until today or yesterday, but I just started getting this error. Any ideas?

Console:
Uncaught TypeError: s.split is not a function............atc.min.js:1

My code in jquery:

```javascript
  (function () {
    if (window.addtocalendar) if (typeof window.addtocalendar.start == "function")
      return;
    if (window.ifaddtocalendar == undefined) {
      window.ifaddtocalendar = 1;
      var d = document,
          s = d.createElement('script'),
          g = 'getElementsByTagName';
      s.type = 'text/javascript';
      s.charset = 'UTF-8';s.async = true;
      s.src = ('https:' == window.location.protocol ? 'https' : 'http') + '://addtocalendar.com/atc/1.5/atc.min.js';
      var h = d[g]('body')[0];h.appendChild(s);
    }
  })();
```

**Comment by theroux** [comment]
I am also getting this error.

**Comment by Nicolai8** [comment]
Got the same error:

the error occurs when script checks if element's class contains "addtocalendar" but JS .className is undefined:

    var s = r[i].className;
    if (s.split(" ").indexOf("addtocalendar") != -1) {

**Comment by sambulance** [comment]
Also having this error. I have narrowed it down to the use of inline SVG on a page. `className` is undefined for SVG. Easiest way to fix would be to check for `s` before splitting:
```
var s=r[i].className;
if(s.length){
	if(s.split(" ").indexOf("addtocalendar")!=-1){
		// ...
	}
}
```

**Comment by theroux** [comment]
@sambulance +1. Pretty sure i was using SVG when I ran into this error.

I can't tell if anyone is maintaining this, but it doesn't hurt to do a PR?

**Comment by sambulance** [comment]
@theroux I was going to do a PR but the code that needs modifying is hosted by @atc-master and not part of the Git repo.

http://addtocalendar.com/atc/1.5/atc.min.js

**Comment by theroux** [comment]
ha. i'm batting 0 today. sorry!

**Comment by felipecruz91** [comment]
Hi,

As @sambulance said, due to the fact that the atc.min.js file is not part of the Git repo, I did the following workaround that I hope can be helpful:

```javascript
    setTimeout(function () {

        if (window.addtocalendar) if (typeof window.addtocalendar.start == "function") return;

        if (window.ifaddtocalendar == undefined) {

            if($(document).find('.addtocalendar').length == 0) return; // line added

            window.ifaddtocalendar = 1;
            var d = document, s = d.createElement('script'), g = 'getElementsByTagName';
            s.type = 'text/javascript'; s.charset = 'UTF-8'; s.async = true;
            s.src = ('https:' == window.location.protocol ? 'https' : 'http') + '://addtocalendar.com/atc/1.5/atc.min.js';
            var h = d[g]('body')[0]; h.appendChild(s);
        };
    }, 1);
```
### Explanation ###

I just had to put the code inside the ```setTimeout``` function in order to wait for the ```<span class="addtocalendar atc-style-blue">``` HTML to be generated from my server side. After that, I just check  if there is any element in my DOM whose class is "addtocalendar". If not, I do not load the atc.min.js file:

```if($(document).find('.addtocalendar').length == 0) return;```

**Comment by atc-master** [comment]
Fixed.

**Comment by ethanclevenger91** [comment]
Can this fix be pushed to the bower version?

**Comment by atc-master** [comment]
Oh, sorry. Updated now.

**Comment by davidarnarsson** [comment]
This is still broken, 
`
            for (var i = 0; i < r.length; i++) {
                var s = r[i].className;
                if (s.length && s.split(" ").indexOf("addtocalendar") != -1) {
                    var o = addtocalendar.loadSettings(r[i]);
                    var u = o["calendars"].length == 1;
                    var a = "http:";
`

className is undefined in IE11 for the SVG filter directive <fefunca>.
